version: '3'
services:
  app:
    container_name: an_app
    image: an_app
    build:
      context: ./
      args:
        - FAKE_ENV_VAR=${FAKE_ENV_VAR} # this wont work and the address will not be schanged
      dockerfile: ./dockerfiles/Dockerfile
    volumes:
      - ./config/config.json:/xmrig/build/config.json
    command: /xmrig/start-xmrig.sh
    env_file:
      - ./environment/.env